services:
  - type: web
    name: face-detection-app
    env: python
    buildCommand: pip install -r requirements.txt && pip install -e .
    startCommand: python app.py
    plan: free
    healthCheckPath: /
    healthCheckTimeout: 300
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.9
