services:
  - type: web
    name: face-detection-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 --threads 1 --timeout 0 app:app
    plan: free
    healthCheckPath: /
    healthCheckTimeout: 300
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: WEB_CONCURRENCY
        value: 1
      - key: PYTHONUNBUFFERED
        value: true
